aspiers/stow

- bin/stow.in
- t/cli_options.t
- The `sanitize_path_options` functions remove all trailing
and leading spaces. So any valid directory like `" 123"`,
`"123" ` can not be used
- Also if there are two directories `" 123"` and `"123"`, and if
user pick the `" 123"` as option to `-d` or `-t`, then stow pick
directory `"123"` as the argument instead of `" 123"` as user want.
```
$ STOW_DIR=. stow -n -v3 -t \ 123 456
stow dir is /tmp/test
stow dir path relative to target 123 is ..
cwd now 123
cwd restored to /tmp/test
cwd now 123
Planning stow of package 456...
Stowing contents of ../456 (cwd=/tmp/test/123)
Planning stow of package 456... done
cwd restored to /tmp/test
WARNING: in simulation mode so not modifying filesystem.
```
- This commit remove the check in `sanitize_path_options` function,
and now stow can work with …
> Allow directory with trailing and leading spaces

- MANIFEST.SKIP
- build-docker.sh
- docker/Dockerfile
- docker/bootstrap-perls.sh
- docker/run-stow-tests.sh
- test-docker.sh
* Use docker to locally run tests on multiple perl versions
* perlbrew used to install multiple perls
* perl environments bootstrapped when image built
* Based on travis configuration
* Adds docker folder to MANIFEST.SKIP
* Running image runs all tests.
* If exit with no error, then all tests pass.
* ./build-docker.sh builds stow testing image.
* ./test-docker.sh runs stow testing image.
* Assumes built with options in build-docker.sh
* *-docker.sh scripts added to MANIFEST.SKIP
> Added docker files for local testing.

- MANIFEST
- bin/stow.in
- lib/Stow.pm.in
- lib/Stow/Util.pm.in
- t/dotfiles.t
This is a PR out of the patch that I [submitted to stow-devel](http://lists.gnu.org/archive/html/stow-devel/2016-05/msg00000.html) to allow for special processing for dotfiles. I use GNU stow to manage my dotfiles, but found it a bit hard to maintain an apparently empty Stow folder, which is full of hidden files.
To address this, the idea is to have a command-line option `--dotfiles` that would have Stow check if the files/folders to stow start with `dot-` (though I should make the prefix configurable...). In this case, Stow replaces the `dot-` prefix by an actual dot (`.`), turning the link target into a proper hidden file.
I am not a skilled Perl developer, so the code is probably rough around the edges. However, if this is a viable approach then I'm definitely up for polishing it and …
> Special processing for dotfiles

- THANKS
- bin/chkstow.in
Thanks to Matan Nassau for reporting this deficiency.
> make chkstow honour $STOW_DIR environment variable

- bin/stow.in
- t/cli.t
Also add a unit test for this.
Fixes #34: https://github.com/aspiers/stow/issues/34
> Return non-zero exit code when invalid option is specified (#34)

- README.md
- bin/stow.in
- doc/stow.texi
- lib/Stow.pm.in
De-emphasise the package management aspects, since these days almost everyone prefers to use modern package managers such as rpm / dpkg / Nix for (system-wide) package management.
Also include more popular modern use cases for Stow such as management of dotfiles and software compiled in the user's `$HOME` directory.
Fixes #22: https://github.com/aspiers/stow/issues/22
> Fix old descriptions of Stow (#22)

- Build.PL
- MANIFEST
- META.json
- META.yml
- NEWS
- bin/stow.in
- doc/stow.texi
- t/cli_options.t
- t/rc_options.t
- t/testutil.pm
This is a rebase and slightly revamp of the excellent work from @cledoux in #13.  I've fixed a few things:
- Rebased and dropped `.gitignore` tweak which is already in `master`.
- The doc comments for `get_config_file_options()` were prematurely updated - now fixed.
- Undefined environment variables should not be expanded to the empty string with a warning , since the most likely scenario is that the user forgot to set them.  In this case Stow has no way of knowing what the right thing to do is, therefore it should die with a helpful error.
- Environment variables are not allowed to contain spaces, so I changed this code to test variables with underscores instead.
- I squashed a few commits so that the history is more atomic, e.g. avoiding adding a new function which isn't used yet, or …
> Perform shell expansion on the contents of .stowrc

- bin/stow.in
- build-docker.sh
- docker/Dockerfile
- test-docker.sh
Fixes #34, I din't write the test that goes along because it would have needed to pull a new dependency ([Test::Exit](https://metacpan.org/pod/Test::Exit)) just for it.
There is also 2 minor changes I had to do to build to build the project correctly on NixOS, namely:
- making the scripts running outside of docker more portable
- fixing the Dockerfile
> return exit code 1 when unknown option 

- .travis.yml
Something weird happened with
https://travis-ci.org/aspiers/stow/jobs/551290921 after merging #42,
as shown below.  Maybe removing texi2html from the list of packages
for Travis to install will help.
```
Installing APT Packages
15.50s$ travis_apt_get_update
0.11s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install texinfo texlive texi2html
Reading package lists...
Building dependency tree...
Reading state information...
Package texinfo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
info install-info
E: Package 'texinfo' has no installation candidate
E: Unable to locate package texi2html …
```
> Fix Travis failure after merging #42

- AUTHORS
- README.md
- THANKS
The source code has been through a rather complicated journey, and it's occasionally useful to understand this history from CVS to a private Subversion repository to its current location in git.  So document this more thoroughly, and ensure that everyone involved is in the `THANKS` file.
> Improve the history of individual contributions and repositories

- bin/stow.in
If the HOME environment variable is not defined, Stow will throw warnings along the lines of:
Use of uninitialized value $ENV{"HOME"} in concatenation(.) or string at /usr/bin/stow line 590, <DATA> line 18.
because it assembles the string `$ENV{HOME}/.stowrc`. This patch avoids dereferencing `$ENV{HOME}` if it is not defined.
I've had this change in production on our systems for a while because a piece of automation doesn't set HOME before invoking `stow`.
> Avoid dereferencing $ENV{HOME} if it is undefined

- Build.PL
- META.json
- META.yml
- NEWS
- bin/stow.in
- configure.ac
- doc/HOWTO-RELEASE
- t/rc_options.t
stow 2.3.0 added external runtime dependencies on Hash::Merge and
Clone::Choose. Historically stow hasn't had runtime dependencies other
than Perl itself, which is a useful property if you're managing the
installation of Perl using stow; the bootstrapping instructions in
stow's manual would need updating to describe how to install these two
modules (and any dependencies they have now or in the future) as well.
However, Hash::Merge is much more general than stow actually needs, so
replace the merge() call with a few lines of equivalent code -- this
avoids the external dependencies, and is clearer than the merge()
call.
Many thanks to Adam Sampson for this patch:
https://lists.gnu.org/archive/html/bug-stow/2019-06/msg00001.html
> Remove dependencies on Hash::Merge and Clone::Choose

- THANKS
- t/cli.t
`t/cli.t` calls scripts which run with the first perl found in the user's `PATH` (usually the system perl), not with the perl used for the build, as reported here:
- https://rt.cpan.org/Ticket/Display.html?id=129944
Thanks to Slaven Rezic for spotting this and reporting it!
> cli.t: test with the right Perl executable

- doc/stow.texi
This should have been part of 182acbbb64425bf95008cb6d42d266f6185032c9
when the option was first added.
This commit basically just copies the help text from stow.in into the
texinfo manual.
> Mention the dotfiles option in the manual

- .coveralls.yml
- .github/workflows/test.yml
- MANIFEST.SKIP
Travis is no longer free, so move to GitHub.  (In the future ideally we should reduce dependencies on proprietary platforms.)
> Port Travis CI workflow to a GitHub CI workflow

- lib/Stow.pm.in
- t/dotfiles.t
Fixes http://savannah.gnu.org/bugs/?56727 and #33.
Problem was that when running stow_contents/unstow_contents recursively from
stow_node/unstow_node the information for the source path (without the dot- to
. transformation) was lost.
In the case of stow_contents, each time it's called from stow_node `../` it's prefixed to the source. The solution there is just to keep track of the level of recursion and delete as many dots as levels.
In the case of unstow_contents the solution is just to provide the source from unstow_node.
> Fixes 'dot-' preprocessing fails for dot-directories (#33, Savannah#56727)

- docker/Dockerfile
This patch fixes the return error 100 that currently happens when trying to run the build script with docker.
```bash
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update -qq && apt-get install -y -q autoconf bzip2 cpanminus gawk git libssl-dev make patch perlbrew texinfo texlive texi2html && apt-get clean && rm -rf /var/lib/apt/lists/*'
returned a non-zero code: 100
```
> fix dockerfile apt-get without force-yes

- bin/stow.in
- doc/stow.texi
- t/cli_options.t
- t/rc_options.t
- t/testutil.pm
- Use `shellwords` to parse `.stowrc` files from `Text::ParseWords`
- Add test for `.stowrc` parsing with quotes
- Add `stow directory` to `tmp-testing-trees` for testing
This change allows `.stowrc` arguments to be parsed similar to shell arguments, where quotes can be used to group an argument with spaces.
However, this change affects the behavior in --ignore, --defer, --override.
--ignore=\$HOME => (?^:$HOME\z)
--defer=\$HOME => (?^:\A$HOME)
--override=\$HOME => (?^:\A$HOME)
Hi, this PR is in regards to #15. Other than the tests mentioned (`rc_options.t`, Test that environment variable expansion is applied. for ignore, defer, and override), everything passes.
I am using `shell_words` but I also did it with `parse_line(" ", 0, $line) and it had the same effect of breaking that test.
My …
> Use `shellwords` for `.stowrc` parsing

- bin/stow.in
Perl 5.40.0 extended the scope of the precedence warning to include ternary operators.
<https://perldoc.perl.org/5.40.0/perldelta>
> avoid precedence warning

- INSTALL.md
- Makefile.am
- NEWS
- aclocal.m4
- doc/HOWTO-RELEASE
> make build of PDF optional to avoid LaTeX dependency

- NEWS
- doc/stow.texi
- lib/Stow.pm.in
- t/dotfiles.t
- t/ignore.t
- t/testutil.pm
If `--dotfiles` was enabled, files in the package such as `dot-gitignore` would be translated to `.gitignore` and then ignored by the default ignore list.  However any file named `dot-*` in a package is obviously intended to be stowed as a dot file, so should not be ignored.
To fix this, ignore based on the name in the package, not the potentially translated name used for stowing.
This was first reported in https://github.com/aspiers/stow/issues/75#issuecomment-2336643249.
> ignore based on package dirent name prior to `dot-` adjustment
